---
title: "Steam Video Game Popularity"
author: "Alex Erickson"
description: "Exploring player activity in Steam video games."
format: html
execute:
  warning: false
  message: false
---

A TidyTuesday dataset from March 16, 2021 that contains monthly player activity for games on Steam.



```{r}
library(dplyr)
library(ggplot2)

games <- read.csv("games.csv")

games_select <- filter(
  games,
  year == 2021,
  month == "January",
  gamename == "Apex Legends" |
    gamename == "Rust" |
    gamename == "Rocket League" |
   gamename == "Dota 2" |
    gamename == "Team Fortress 2" |
    gamename == "Counter-Strike: Global Offensive"
)

ggplot(games_select, aes(x = gamename, y = avg)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(
    title = "Player Activity on Steam in January 2021",
    x = "Game",
    y = "Average Players"
  ) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


This bar chart compares the average concurrent players for six steam games in January 2021 
(Counter-Strike: Global Offensive, Dota 2, Team Fortress 2, Rust, Apex Legends, and Rocket 
League). Counter-Strike: Global Offensive had the highest average of 743,210 concurrent players, 
followed by Dota 2 with 432,672. Rust averaged 142,117 players while Team Fortress 2, Apex 
Legends, and Rocket League all had fewer than 100,000 concurrent active players. These results 
convey a large difference in activity between games withinn the month of January 2021.

Sources:

R for Data Science. (2021, March 16). TidyTuesday: Video Games and Sliced. Dataset and documentation.

michau96. (n.d.). Popularity of games on Steam [Dataset]. Kaggle. Kaggle dataset.

